-- Seed data: 42 taches, 12 metiers, metiers_taches associations
-- Generated from fiches-completes-42-taches-12-metiers.md

-- =========================
-- taches (42 rows)
-- =========================
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F01$t$, $t$Gestion et tri des e-mails$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F03$t$, $t$Rédaction et correction de documents professionnels$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F04$t$, $t$Transcription et résumé de réunions et interviews$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F05$t$, $t$Planification de rendez-vous et gestion d'agenda$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F07$t$, $t$Veille sectorielle et recherche d'informations$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F08$t$, $t$Analyse de données et création de rapports$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F11$t$, $t$Extraction d'informations et préparation de la saisie$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F12$t$, $t$Classement et indexation de documents$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F13$t$, $t$Analyse et comparaison d'un dossier documentaire$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F14$t$, $t$Traduction et adaptation de documents professionnels$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F15$t$, $t$Création de présentations à partir d'un brief$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F16$t$, $t$Organisation de projets et suivi des actions$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F02$t$, $t$Création et planification de contenus pour les réseaux sociaux$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F06$t$, $t$Service client de premier niveau (FAQ)$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F25$t$, $t$Tri et orientation des demandes clients$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F26$t$, $t$Analyse des avis et enquêtes de satisfaction$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F27$t$, $t$Construction de segments de clientèle$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F28$t$, $t$Optimisation des paramètres publicitaires$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F10$t$, $t$Nettoyage, enrichissement et qualification de bases CRM$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F17$t$, $t$Prospection et relances commerciales personnalisées$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F18$t$, $t$Préparation de devis et propositions commerciales$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F19$t$, $t$Catégorisation des transactions comptables$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F20$t$, $t$Rapprochement bancaire et examen des écarts$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F21$t$, $t$Suivi des impayés et relances de paiement$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F22$t$, $t$Suivi des commandes et changements fournisseurs$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F23$t$, $t$Prévision de la demande et préparation des approvisionnements$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F24$t$, $t$Planification d'itinéraires et estimation des délais$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F31$t$, $t$Repérage et comptage d'éléments sur un plan$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F32$t$, $t$Suivi de l'avancement visible d'un chantier$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F33$t$, $t$Hiérarchisation des points de risque d'un chantier$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F29$t$, $t$Préparation de l'examen des candidatures$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F30$t$, $t$Parcours de formation personnalisés$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F09$t$, $t$Génération d'images et de visuels marketing$t$, true, $t$gemini$t$);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F34$t$, $t$Retouche d'image et modification d'éléments$t$, true, $t$gemini$t$);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F35$t$, $t$Variantes de couleurs d'un visuel$t$, true, $t$gemini$t$);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F36$t$, $t$Recherche de plans dans les rushes vidéo$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F37$t$, $t$Premier montage à partir d'une transcription$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F38$t$, $t$Création et traduction de sous-titres$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F39$t$, $t$Nettoyage d'un enregistrement vocal$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F40$t$, $t$Recadrage vidéo pour différents formats$t$, false, null);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F41$t$, $t$Voix off et doublage traduit$t$, true, $t$gemini$t$);
insert into taches (code, titre, limite_connue, ia_alternative_conseillee) values ($t$F42$t$, $t$Génération de séquences vidéo d'illustration$t$, true, $t$gemini$t$);

-- =========================
-- metiers (12 rows)
-- =========================
insert into metiers (slug, nom, description, ordre) values ($t$vente-commercial$t$, $t$Vente / Commercial$t$, $t$Gemini est recommandé pour la prospection et le suivi CRM connectés à Gmail ; ChatGPT en repli si CRM/messagerie Microsoft.$t$, 1);
insert into metiers (slug, nom, description, ordre) values ($t$btp-gestion-de-chantier$t$, $t$BTP / Gestion de chantier$t$, $t$Gemini est recommandé pour la planification et le suivi documentaire ; Claude en second choix pour l'analyse de risques sur de longs rapports.$t$, 2);
insert into metiers (slug, nom, description, ordre) values ($t$comptabilite$t$, $t$Comptabilité$t$, $t$Gemini est recommandé si les outils comptables sont déjà connectés à Sheets ; ChatGPT sinon.$t$, 3);
insert into metiers (slug, nom, description, ordre) values ($t$secretariat-administration$t$, $t$Secrétariat / Administration$t$, $t$Gemini est recommandé pour la gestion d'agenda/mail au quotidien ; c'est l'écart le plus faible des 12 métiers, les 3 IA restent utilisables.$t$, 4);
insert into metiers (slug, nom, description, ordre) values ($t$logistique-supply-chain$t$, $t$Logistique / Supply Chain$t$, $t$Gemini est recommandé pour le suivi fournisseurs et la prévision si les données sont dans Sheets ; un MCP Dynamics 365 est conseillé pour Claude/ChatGPT sinon.$t$, 5);
insert into metiers (slug, nom, description, ordre) values ($t$service-clientele$t$, $t$Service clientèle$t$, $t$Gemini est légèrement devant, mais c'est le métier où les 3 IA sont les plus proches ; le facteur décisif reste l'outil de ticketing utilisé.$t$, 6);
insert into metiers (slug, nom, description, ordre) values ($t$marketing$t$, $t$Marketing$t$, $t$Gemini est nettement devant grâce à la génération/édition d'image et de vidéo native ; Claude est à écarter pour ce métier, sauf pour la stratégie/rédaction pure.$t$, 7);
insert into metiers (slug, nom, description, ordre) values ($t$communication$t$, $t$Communication$t$, $t$La même logique que pour le Marketing s'applique, avec un écart encore plus marqué en faveur de Gemini.$t$, 8);
insert into metiers (slug, nom, description, ordre) values ($t$ressources-humaines$t$, $t$Ressources humaines$t$, $t$Gemini est recommandé pour la présélection de CV et le suivi de formation connectés ; Claude est une alternative solide pour l'analyse qualitative fine des candidatures.$t$, 9);
insert into metiers (slug, nom, description, ordre) values ($t$journalisme$t$, $t$Journalisme$t$, $t$Gemini est recommandé pour la recherche de plans vidéo et le montage ; ChatGPT est correct en repli pour la partie rédactionnelle pure.$t$, 10);
insert into metiers (slug, nom, description, ordre) values ($t$graphisme$t$, $t$Graphisme$t$, $t$Gemini est très largement devant grâce à l'édition d'image conversationnelle ; Claude est quasiment inutilisable seul sur ce métier.$t$, 11);
insert into metiers (slug, nom, description, ordre) values ($t$montage-video$t$, $t$Montage vidéo$t$, $t$Gemini est très largement devant grâce à Gemini Omni (montage conversationnel direct) ; Claude est quasiment inutilisable seul sur ce métier.$t$, 12);

-- =========================
-- metiers_taches associations
-- =========================
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F06$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F10$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F17$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F18$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F21$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F22$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 18 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 19 from metiers m, taches t where m.slug = $t$vente-commercial$t$ and t.code = $t$F27$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F18$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F22$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F23$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F24$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F31$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 18 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F32$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 19 from metiers m, taches t where m.slug = $t$btp-gestion-de-chantier$t$ and t.code = $t$F33$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F19$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F20$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F21$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$comptabilite$t$ and t.code = $t$F22$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F06$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F10$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F22$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$secretariat-administration$t$ and t.code = $t$F30$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F21$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F22$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F23$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F24$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$logistique-supply-chain$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F06$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F10$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F25$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$service-clientele$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F02$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F09$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F10$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F17$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F27$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F28$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 18 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F34$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 19 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F35$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 20 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F36$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 21 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F37$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 22 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F38$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 23 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F39$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 24 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F40$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 25 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F41$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 26 from metiers m, taches t where m.slug = $t$marketing$t$ and t.code = $t$F42$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F02$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F09$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F27$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F34$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F35$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 18 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F38$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 19 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F40$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 20 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F41$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 21 from metiers m, taches t where m.slug = $t$communication$t$ and t.code = $t$F42$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F06$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F11$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F29$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$ressources-humaines$t$ and t.code = $t$F30$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F08$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F25$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F36$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F37$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F38$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F39$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$journalisme$t$ and t.code = $t$F40$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F07$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F09$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F15$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F18$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F34$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F35$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F40$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$graphisme$t$ and t.code = $t$F42$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 1 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F01$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 2 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F03$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 3 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F04$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 4 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F05$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 5 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F09$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 6 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F12$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 7 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F13$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 8 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F14$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 9 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F16$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 10 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F18$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 11 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F26$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 12 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F34$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 13 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F35$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 14 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F36$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 15 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F37$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 16 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F38$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 17 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F39$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 18 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F40$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 19 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F41$t$;
insert into metiers_taches (metier_id, tache_id, ordre) select m.id, t.id, 20 from metiers m, taches t where m.slug = $t$montage-video$t$ and t.code = $t$F42$t$;
