-- Remplace les tirets longs des contenus déjà en base, phrase par phrase,
-- selon le sens (deux-points, virgule, point, parenthèses...). Les mêmes
-- choix ont été appliqués aux fichiers de seed. Chaque remplacement cible un
-- extrait unique : sans effet si le texte a déjà été corrigé.

update taches set titre = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(titre,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where titre ~ '[\u2010-\u2015\u2212]';

update exercices set titre = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(titre,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where titre ~ '[\u2010-\u2015\u2212]';

update exercices set contexte = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(contexte,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where contexte ~ '[\u2010-\u2015\u2212]';

update exercices set donnees = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(donnees,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where donnees ~ '[\u2010-\u2015\u2212]';

update exercices set travail_a_faire = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(travail_a_faire,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where travail_a_faire ~ '[\u2010-\u2015\u2212]';

update prompts set contenu = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(contenu,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where contenu ~ '[\u2010-\u2015\u2212]';

update metiers set nom = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(nom,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where nom ~ '[\u2010-\u2015\u2212]';

update metiers set description = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(description,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where description ~ '[\u2010-\u2015\u2212]';

update glossaire set terme = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(terme,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where terme ~ '[\u2010-\u2015\u2212]';

update glossaire set definition = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(definition,
    $q$Service client de premier niveau $q$ || chr(8212) || $q$ FAQ$q$,
    $q$Service client de premier niveau (FAQ)$q$),
    $q$Cas fictif 1 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 1 : $q$),
    $q$Cas fictif 2 $q$ || chr(8212) || $q$ $q$,
    $q$Cas fictif 2 : $q$),
    $q$De: j.martel@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: j.martel@clientprive.fr, "$q$),
    $q$De: compta@fournitures-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: compta@fournitures-pro.fr, "$q$),
    $q$De: newsletter@archidaily.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@archidaily.com, "$q$),
    $q$De: p.rousseau@mairie-tassin.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: p.rousseau@mairie-tassin.fr, "$q$),
    $q$De: recrutement@archi-jobs.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: recrutement@archi-jobs.fr, "$q$),
    $q$De: s.durand@meridia-archi.fr (interne) $q$ || chr(8212) || $q$ "$q$,
    $q$De: s.durand@meridia-archi.fr (interne), "$q$),
    $q$De: no-reply@edf-entreprises.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: no-reply@edf-entreprises.fr, "$q$),
    $q$De: m.chen@investisseur-immo.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: m.chen@investisseur-immo.com, "$q$),
    $q$De: t.lefebvre@clientprive.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: t.lefebvre@clientprive.fr, "$q$),
    $q$De: greenwashing-solutions@spam-marketing.biz $q$ || chr(8212) || $q$ "$q$,
    $q$De: greenwashing-solutions@spam-marketing.biz, "$q$),
    $q$De: c.moreau@meridia-archi.fr (interne, associé) $q$ || chr(8212) || $q$ "$q$,
    $q$De: c.moreau@meridia-archi.fr (interne, associé), "$q$),
    $q$De: booking@planity.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: booking@planity.com, "$q$),
    $q$De: sophie.leroy92@gmail.com $q$ || chr(8212) || $q$ "$q$,
    $q$De: sophie.leroy92@gmail.com, "$q$),
    $q$De: fournisseur@loreal-pro.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: fournisseur@loreal-pro.fr, "$q$),
    $q$De: urssaf.contact@urssaf.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: urssaf.contact@urssaf.fr, "$q$),
    $q$De: unclient.mecontent@hotmail.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: unclient.mecontent@hotmail.fr, "$q$),
    $q$De: proprietaire.local@immo-lille.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: proprietaire.local@immo-lille.fr, "$q$),
    $q$De: assistante@franchise-coiffure-nationale.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: assistante@franchise-coiffure-nationale.fr, "$q$),
    $q$De: newsletter@lecoiffeur-magazine.fr $q$ || chr(8212) || $q$ "$q$,
    $q$De: newsletter@lecoiffeur-magazine.fr, "$q$),
    $q$" $q$ || chr(8212) || $q$ reçu $q$,
    $q$", reçu $q$),
    $q$Client 1 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 1 : Note 9, "$q$),
    $q$Client 2 : Note 4 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 2 : Note 4, "$q$),
    $q$Client 3 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 3 : Note 10, "$q$),
    $q$Client 4 : Note 6 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 4 : Note 6, "$q$),
    $q$Client 5 : Note 3 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 5 : Note 3, "$q$),
    $q$Client 6 : Note 9 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 6 : Note 9, "$q$),
    $q$Client 7 : Note 8 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 7 : Note 8, "$q$),
    $q$Client 8 : Note 2 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 8 : Note 2, "$q$),
    $q$Client 9 : Note 10 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 9 : Note 10, "$q$),
    $q$Client 10 : Note 5 $q$ || chr(8212) || $q$ "$q$,
    $q$Client 10 : Note 5, "$q$),
    $q$Devis A $q$ || chr(8212) || $q$ Fournisseur "Linéa Pro" :$q$,
    $q$Devis A (Fournisseur "Linéa Pro") :$q$),
    $q$Article 8 $q$ || chr(8212) || $q$ Télétravail$q$,
    $q$Article 8 : Télétravail$q$),
    $q$Campagne A "Nouveaux visiteurs" $q$ || chr(8212) || $q$ ciblage large$q$,
    $q$Campagne A "Nouveaux visiteurs", ciblage large$q$),
    $q$Campagne B "Reciblage" $q$ || chr(8212) || $q$ ciblage des visiteurs$q$,
    $q$Campagne B "Reciblage", ciblage des visiteurs$q$),
    $q$"Le Bistrot du Coin" $q$ || chr(8212) || $q$ restaurant traditionnel$q$,
    $q$"Le Bistrot du Coin", restaurant traditionnel$q$),
    $q$"Sushi Time" $q$ || chr(8212) || $q$ chaîne de 4 restaurants$q$,
    $q$"Sushi Time", chaîne de 4 restaurants$q$),
    $q$"La Table Verte" $q$ || chr(8212) || $q$ restaurant végétarien$q$,
    $q$"La Table Verte", restaurant végétarien$q$),
    $q$"Boulangerie Ferrand" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Boulangerie Ferrand" : Facture n°$q$),
    $q$"Groupe Immo Est" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Groupe Immo Est" : Facture n°$q$),
    $q$"Salon Coiffure Ines" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Salon Coiffure Ines" : Facture n°$q$),
    $q$"Menuiserie Vasseur" $q$ || chr(8212) || $q$ Facture n°$q$,
    $q$"Menuiserie Vasseur" : Facture n°$q$),
    $q$"Cabinet Notarial Reyes" $q$ || chr(8212) || $q$ 2 factures en cours :$q$,
    $q$"Cabinet Notarial Reyes", 2 factures en cours :$q$),
    $q$"École Privée Saint-Marc" $q$ || chr(8212) || $q$ facture de 1 100€$q$,
    $q$"École Privée Saint-Marc" : facture de 1 100€$q$),
    $q$"Start-up TechFlow" $q$ || chr(8212) || $q$ facture de 650€$q$,
    $q$"Start-up TechFlow" : facture de 650€$q$),
    $q$"Cabinet Médical Ost" $q$ || chr(8212) || $q$ facture de 95€$q$,
    $q$"Cabinet Médical Ost" : facture de 95€$q$),
    $q$"Mariage Petit" $q$ || chr(8212) || $q$ 45 min de préparation$q$,
    $q$"Mariage Petit", 45 min de préparation$q$),
    $q$"Entreprise TechNova" $q$ || chr(8212) || $q$ plateaux repas$q$,
    $q$"Entreprise TechNova", plateaux repas$q$),
    $q$"Anniversaire Famille Roy" $q$ || chr(8212) || $q$ gâteau et pièces$q$,
    $q$"Anniversaire Famille Roy", gâteau et pièces$q$),
    $q$"Cocktail Cabinet Notarial" $q$ || chr(8212) || $q$ service prévu$q$,
    $q$"Cocktail Cabinet Notarial", service prévu$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$),
    $q$n'a 
pas commencé $q$ || chr(8212) || $q$ l'entreprise de démolition$q$,
    $q$n'a 
pas commencé : l'entreprise de démolition$q$),
    $q$une seule séquence de 4 secondes $q$ || chr(8212) || $q$ trop d'éléments$q$,
    $q$une seule séquence de 4 secondes : trop d'éléments$q$),
    $q$(jour, format $q$ || chr(8212) || $q$ post/story/reel, thème$q$,
    $q$(jour, format (post/story/reel), thème$q$),
    $q$orienté crédibilité B2B $q$ || chr(8212) || $q$ pas un ton grand public$q$,
    $q$orienté crédibilité B2B, pas un ton grand public$q$),
    $q$temps de trajet indiqués $q$ || chr(8212) || $q$ si ce n'est pas le cas$q$,
    $q$temps de trajet indiqués. Si ce n'est pas le cas$q$)
where definition ~ '[\u2010-\u2015\u2212]';
