-- 0018 : retrait de la table glossaire (3 octobre 2026)
--
-- À EXÉCUTER SEULEMENT APRÈS la mise en ligne de la nouvelle interface
-- (fusion dans main). L'ancienne interface, encore en ligne, lit cette table
-- (page « Comprendre les IA » et recherche) : la supprimer avant casserait
-- ces deux écrans.
--
-- La nouvelle interface n'affiche plus de glossaire : chaque mot technique est
-- expliqué là où il apparaît. Les conditions et les mentions légales ne le
-- citent plus.
--
-- Rien n'est perdu : les 8 définitions restent dans
-- supabase/seed/seed_0006_glossaire.sql. Pour recréer la table, reprendre sa
-- définition dans 0001_init.sql, ses droits dans 0015 et 0016, puis ce fichier
-- de contenu.
--
-- Suppression définitive : la requête est préparée, c'est l'utilisateur qui
-- clique sur Run (règle B2). La politique de lecture part avec la table.
-- Migration rejouable.

drop table if exists glossaire;
